# true color
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"

setw -g mode-keys vi

# Plugins
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Mouse
set -g mouse on

# Window indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Split with current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g status on
set -g status-position bottom
set -g status-interval 1

# No global bg to prevent full bar coloring
set -g status-style "bg=default,fg=#859289"

set -g status-left ""
set -g status-right ""
set -g status-justify centre

setw -g window-status-separator ""

setw -g window-status-format "#[fg=#859289,nobold] #I:#W "

setw -g window-status-current-format "#[fg=#859289,bg=#374145,bold] #I:#W "

# Load TPM
run '~/.tmux/plugins/tpm/tpm'
